export { CurveSeparator } from './CurveSeparator.jsx'
export { Arrow } from './Arrow.jsx'
export { Waves } from './Waves.jsx'
export { Email } from './Email'
export { Message } from './Message'
export { Person } from './Person'
export { Telephone } from './Telephone'